spring.application.name=acoustic-sentinel-backend
server.port=8080

# Bypass the URI string parser completely
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=acoustic_sentinel